CREATE TABLE CUSTOMERS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  firstname VARCHAR(255),
  lastname VARCHAR(255)
);

CREATE SEQUENCE CUSTOMERS_SEQUENCE START WITH 1000 INCREMENT BY 1;

INSERT INTO CUSTOMERS (firstname, lastname) VALUES ('Antonio', 'Romano');
INSERT INTO CUSTOMERS (firstname, lastname) VALUES ('Diego Armando', 'Maradona');
INSERT INTO CUSTOMERS (firstname, lastname) VALUES ('Zinedine', 'Zidane');
INSERT INTO CUSTOMERS (firstname, lastname) VALUES ('Valentino', 'Rossi');
